version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run: python -m venv venv
      - run: . venv/bin/activate && pip install -r requirements.txt
      - run: . venv/bin/activate && pip install pytest
      - run: . venv/bin/activate && pytest tests

workflows:
  test_and_deploy:
    jobs:
      - test
