version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  python: circleci/python@2.1.1

jobs:
  project_checkout:
    machine:
      image: ubuntu-2204:edge
      docker_layer_caching: true
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  etl:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Extract Data
          command: python etl.py extract_data

      - run:
          name: Transform Data
          command: python etl.py transform_data

      - run:
          name: Validate Data
          command: python etl.py validate_data

      - run:
          name: Load Data
          command: python etl.py load_data

      - persist_to_workspace:
          root: .
          paths:
            - .
            
      - run:
          name: Verify file exists
          command: |
            ls -l data
            cat data/crypto.md

      - store_artifacts:
          path: data/crypto.md
          destination: output-data
        
  upload:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: .

      - aws-cli/setup:
          profile_name: default
      - aws-cli/role_arn_setup:
          profile_name: new-profile
          role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-role
          source_profile: default

      - run:
          name: Create a publicly accessible S3 bucket
          command: |
            aws s3api create-bucket --bucket ${S3_BUCKET} --region ${AWS_REGION} --no-cli-pager
            echo "Bucket created: ${S3_BUCKET}"
            aws s3api put-public-access-block --bucket ${S3_BUCKET} --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false --no-cli-pager
            aws s3api put-bucket-ownership-controls --bucket ${S3_BUCKET} --ownership-controls 'Rules=[{ObjectOwnership=BucketOwnerPreferred}]' --no-cli-pager

      - run:
          name: Upload publicly accessible page to S3
          command: |
            aws s3 cp data/crypto.md s3://${S3_BUCKET}/crypto.md --acl public-read
            FULL_URL="https://${S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/crypto.md"
            echo "Uploaded to: ${FULL_URL}"

workflows:
  ci-cd:
    jobs:
      - project_checkout
      - etl:
          requires:
            - project_checkout
      - upload:
          requires:
            - etl
