version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  python: circleci/python@2.1.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run ETL pipeline
          command: python etl.py

      - run:
          name: List files before upload
          command: |
            echo "Current directory:"
            pwd
            echo "Listing files in data directory:"
            ls -l data/
            echo "Listing files in the root directory:"
            ls -l

      - persist_to_workspace:
          root: .
          paths:
            - data/crypto.md

      - aws-cli/setup:
          profile_name: default

      - run:
          name: Create S3 bucket if it doesn't exist
          command: |
            aws s3 ls s3://${S3_BUCKET}/ || aws s3 mb s3://${S3_BUCKET} --region ${AWS_REGION}

      - run:
          name: Configure bucket for public access
          command: |
            # Disable block public access
            aws s3api put-public-access-block --bucket ${S3_BUCKET} --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false

            # Set bucket policy for public read
            aws s3api put-bucket-policy --bucket ${S3_BUCKET} --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "AllowPublicReadAccess",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::${S3_BUCKET}/*"
                }
              ]
            }'

      - run:
          name: Upload to S3 and print URL
          command: |
            aws s3 cp data/crypto.md s3://${S3_BUCKET}/crypto.md
            echo "Uploaded to: https://${S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/crypto.md"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
