# name: CI for ETL Pipeline

# on:
#   push:
#     branches: [ main ]

# jobs:
#   run-etl:
#     runs-on: ubuntu-22.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run ETL pipeline
#         run: python etl.py

#       - name: List files *before* upload
#         run: |
#           echo "Current directory:"
#           pwd
#           echo "Listing files in data directory:"
#           ls -l data/
#           echo "Listing files in the root directory:"
#           ls -l
#       - name: Upload SQLite DB as artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: crypto-database
#           path: data/crypto.db
